pipeline {
    agent {
        docker {
            image 'node:14-buster-slim'
            args '-p 3002:3000 --privileged'
        }
    }
    stages {
        stage('Build') {
            steps {
                sh 'npm install'
            }
        }
        stage('Test') {
            steps {
                sh "chmod +x ./jenkins/scripts/test.sh"
                sh './jenkins/scripts/test.sh'
            }
        }
        stage('Deliver') {
            steps {
                sh "chmod +x ./jenkins/scripts/deliver.sh"
                sh './jenkins/scripts/deliver.sh'
            }
        }
    }
}
